embedding_dim: 32
out_dim: 1
out_activation: 'sigmoid'
depth: 3
heads: 6
attn_dropout: 0.2
ff_dropout: 0.2
explainable: True
numerical_embedding_type: 'ple'
numerical_bins: 64

patience: 10
epochs: 100
lr: 0.0001
weight_decay: 0.0001